volumes:
  mysql_data:
  
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./db/seeds/table_setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/seeds/triggers.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./db/seeds/dummy-data.sql:/docker-entrypoint-initdb.d/3.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "
      sleep 15 &&
      flask run -h 0.0.0.0 -p 5000
      "


